baseURL = "https://zhenrongwu.github.io"
languageCode = "zh-tw"
DefaultContentLanguage = "zh-tw"
title = "Zhenrong's Blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
disqusShortname = "myblog-7gyc4scw0e"

# Google Analytics
googleAnalytics = "G-LEED6SX3PW"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true