[tw]
title = "我的部落格"
weight = 1
LanguageName = "TW"
contentDir = "content/traditional-chinese"

[en]
title = "My Blog"
description = ""
contentDir = "content/english" 
weight = 2
LanguageDirection = "rtl" 
LanguageName = "EN"