  [[main]]
  name = "首頁"
  identifier = "main"
  weight = 100
  url = "/tw"

  [[main]]
  name = "文章"
  weight = 200
  identifier = "posts"
  url = "/tw/post"

  [[main]]
  name = "關於"
  weight = 300
  identifier = "about"
  url = "/tw/about"

  [[main]]
  name = "聯絡"
  weight = 400
  identifier = "contact"
  url = "/tw/contact"