version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      vite:
        patterns:
          - vite
          - "@vitejs/*"
          - vitest
          - "@vitest/*"
      minor-and-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: eslint
        update-types: ["version-update:semver-major"]
      - dependency-name: "@eslint/js"
        update-types: ["version-update:semver-major"]
